#pragma config(Sensor, S2,     button2,        sensorNone)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speedright = 50;
	int speedleft = 0;
	int spiral = 1;
	int WallFollowing = 2;
	int straight = 3;
	int wfcount = 0;
	int mode = spiral;

	while(true)
	{
		if(mode == spiral)
		{

			motor[right] = speedright;
			motor[left] = speedleft;

			wait1Msec(1000);



			speedleft = speedleft + 5;
			speedright = speedright + 5;

			if(speedleft == 100)
			{
				  resetMotorEncoder(left);

					mode = straight;

			}


			if(SensorValue(button2) ==1)
			{
				mode = WallFollowing;

			}




		}

		if(mode == straight)
		{

			motor[left] = 50;
			motor[right] = 50;


				if (getMotorEncoder(left) > 3000)
				{
					speedright = 50;
					speedleft = 0;
					mode = spiral;
				}

			if(SensorValue(button2) ==1)
			{
				wfcount = 0;
				mode = WallFollowing;
			}

		}

 		if(mode == WallFollowing)
 		{


			 wfcount = wfcount + 1;



	while(SensorValue(button2) ==0)
			{
				motor[left] = 50;
				motor[right] = 50;

			}

			motor[left] = -50;
			motor[right] = -50;
			wait1Msec(1500);

			motor[left] = 0;
			motor[right] = 75;
			wait1Msec(750);

			while(SensorValue(button2) ==0)
			{
				motor[left] = 100;
				motor[right] = 40;
			}


				if (wfcount == 5)
				{
					motor[left] = -50;
					motor[right] = -50;
					wait1Msec(1000);

					motor[left] = 50;
					motor[right] = 0;
					wait1Msec(1500);

					resetMotorEncoder(left);

					mode = straight;
				}






				}
			}



	}
