#pragma config(Sensor, S2,     button,         sensorNone)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speedright = 50;
	int speedleft = 0;
	int spiral = 1;
	int WallFollowing = 2;
	int straight = 3;
	int mode = spiral;

	while(true)
	{
		if(mode == spiral)
		{

			motor[right] = speedright;
			motor[left] = speedleft;

			speedleft = speedleft + 10;
			speedright = speedright + 10;
			wait1Msec(3000);

		}

		if(mode == straight)
		{
			motor[left] = 50;
			motor[right] 50;
		}

	}




}
